package com.familya.treeaccess.adapter.in.grpc;

import com.familya.platform.error.StaleProjectionException;
import com.familya.platform.telemetry.PlatformMetrics;
import com.familya.treeaccess.application.port.out.TreeRepository;
import com.familya.treeaccess.domain.model.AuthorizationProjection;
import com.familya.treeaccess.domain.model.Tree;
import io.grpc.stub.StreamObserver;
import net.devh.boot.grpc.server.service.GrpcService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Optional;
import java.util.UUID;

/**
 * Deadline-bound emergency authorization lookup. Other services fall
 * back to this RPC when their local membership projection is missing
 * or stale. The RPC reads the local projection table; it is therefore
 * only as authoritative as the projection is fresh. The
 * {@code STALE} outcome is returned when the projection's revision is
 * below the caller's expected revision.
 *
 * <p>The protobuf message types live in the {@code contracts/grpc/treeaccess}
 * directory. In a CI environment they are generated by the protobuf
 * compiler; this file uses lightweight POJOs that mirror the proto
 * shape so the service compiles without the toolchain in this session.
 * The runtime contract (field numbers, types) is identical.</p>
 */
@GrpcService
public class TreeAccessLookupService extends TreeAccessProtoGrpc.TreeAccessLookupImplBase {

    private static final Logger LOG = LoggerFactory.getLogger(TreeAccessLookupService.class);

    private final TreeRepository repo;
    private final PlatformMetrics metrics;

    public TreeAccessLookupService(TreeRepository repo, PlatformMetrics metrics) {
        this.repo = repo;
        this.metrics = metrics;
    }

    @Override
    public void authorize(TreeAccessProto.AuthorizeRequest request,
                          StreamObserver<TreeAccessProto.AuthorizeResponse> responseObserver) {
        metrics.mutationAccepted("tree-access-service", "emergency_authorize");
        TreeAccessProto.AuthorizeResponse.Builder b = TreeAccessProto.AuthorizeResponse.newBuilder();
        try {
            UUID treeId = UUID.fromString(request.getTreeId());
            UUID userId = UUID.fromString(request.getUserId());
            long expectedRevision = request.getExpectedRevision();

            Optional<Tree> treeOpt = repo.findTree(treeId);
            if (treeOpt.isEmpty()) {
                b.setOutcome(TreeAccessProto.AuthorizeResponse.Outcome.NOT_FOUND);
                responseObserver.onNext(b.build());
                responseObserver.onCompleted();
                return;
            }
            Tree tree = treeOpt.get();
            b.setRevision(tree.revision()).setEpoch(tree.epoch());

            if (tree.ownerUserId().equals(userId)) {
                b.setOutcome(TreeAccessProto.AuthorizeResponse.Outcome.AUTHORIZED)
                 .setRole("ADMIN").setCanEdit(true).setCanView(true);
                responseObserver.onNext(b.build());
                responseObserver.onCompleted();
                return;
            }

            Optional<AuthorizationProjection> proj = repo.findProjection(treeId, userId);
            if (proj.isEmpty()) {
                b.setOutcome(TreeAccessProto.AuthorizeResponse.Outcome.NOT_FOUND);
            } else {
                AuthorizationProjection p = proj.get();
                if (p.revoked()) {
                    b.setOutcome(TreeAccessProto.AuthorizeResponse.Outcome.DENIED);
                } else if (p.revision() < expectedRevision) {
                    b.setOutcome(TreeAccessProto.AuthorizeResponse.Outcome.STALE)
                     .setRole(p.role() == null ? "" : p.role().name());
                } else {
                    b.setOutcome(TreeAccessProto.AuthorizeResponse.Outcome.AUTHORIZED)
                     .setRole(p.role() == null ? "" : p.role().name())
                     .setCanEdit(p.canEdit())
                     .setCanView(p.canView());
                }
            }
        } catch (StaleProjectionException spe) {
            LOG.debug("Emergency lookup stale tree={} user={}", request.getTreeId(), request.getUserId());
            b.setOutcome(TreeAccessProto.AuthorizeResponse.Outcome.STALE);
        } catch (IllegalArgumentException iae) {
            b.setOutcome(TreeAccessProto.AuthorizeResponse.Outcome.UNKNOWN);
        }
        responseObserver.onNext(b.build());
        responseObserver.onCompleted();
    }

    @Override
    public void getTreeRevision(TreeAccessProto.GetTreeRevisionRequest request,
                                StreamObserver<TreeAccessProto.GetTreeRevisionResponse> responseObserver) {
        TreeAccessProto.GetTreeRevisionResponse.Builder b = TreeAccessProto.GetTreeRevisionResponse.newBuilder();
        try {
            UUID treeId = UUID.fromString(request.getTreeId());
            Optional<Tree> tree = repo.findTree(treeId);
            if (tree.isPresent()) {
                b.setFound(true)
                 .setRevision(tree.get().revision())
                 .setEpoch(tree.get().epoch())
                 .setState(tree.get().state().name());
            } else {
                b.setFound(false);
            }
        } catch (IllegalArgumentException iae) {
            b.setFound(false);
        }
        responseObserver.onNext(b.build());
        responseObserver.onCompleted();
    }
}