package vn.giapha.research.identity.application.service;

import java.time.Instant;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Sanitized, deterministic users.json fixtures for the identity migration
 * (Task 17 DoD). The exact BCrypt hashes are intentionally left as
 * {@code null} — they are populated at fixture-load time by
 * {@link #withGeneratedHashes(PasswordHasher)} which calls the real
 * {@link PasswordHasher} so the committed plaintexts round-trip through the
 * production verifier.
 *
 * <p>Why this shape? Legacy users.json was authored with bcryptjs at cost 12
 * ($2a$). After migration the Spring side authenticates with
 * {@link PasswordHasher} which also encodes at $2a$12; a fixture whose hashes
 * are generated by the same encoder proves round-trip authenticity without
 * committing a fake hash that the production code would later refuse.
 *
 * <p>Covered scenarios:
 * <ul>
 *   <li>credential user with verified email — golden plaintext authenticates
 *       (Task 17 DoD);</li>
 *   <li>credential user with five failed attempts and a future {@code lockedUntil}
 *       — lockout preserved verbatim;</li>
 *   <li>credential user with a pending email verification token;</li>
 *   <li>Google and Facebook OAuth users, both with a verified email and an
 *       {@code oauth_accounts} row;</li>
 *   <li>a duplicate external ID — the transformer must surface it, not merge;</li>
 *   <li>a duplicate normalized email — the database must reject the second
 *       user (Task 17.4 constraint-safety).</li>
 * </ul>
 */
public final class IdentityGoldenCorpus {

    private IdentityGoldenCorpus() {}

    public static final String CREDENTIAL_USER_ID = "u_credential_001";
    public static final String LOCKED_USER_ID = "u_locked_002";
    public static final String PENDING_USER_ID = "u_pending_003";
    public static final String GOOGLE_USER_ID = "u_google_004";
    public static final String FACEBOOK_USER_ID = "u_facebook_005";
    public static final String DUPLICATE_USER_ID = "u_credential_001";
    public static final String EMAIL_CLASH_USER_ID = "u_email_clash_006";

    public static final String CREDENTIAL_PLAINTEXT = "golden-credential-plaintext";
    public static final String LOCKED_PLAINTEXT = "golden-locked-plaintext";
    public static final String PENDING_PLAINTEXT = "golden-pending-plaintext";

    public static final Instant FIXED_CREATED_AT = Instant.parse("2024-01-02T03:04:05Z");
    public static final Instant FIXED_UPDATED_AT = Instant.parse("2024-02-12T08:09:10Z");
    public static final Instant FIXED_VERIFIED_AT = Instant.parse("2024-01-09T12:34:56Z");
    public static final Instant FIXED_TOKEN_EXPIRES_AT = Instant.parse("2024-01-03T03:04:05Z");
    public static final Instant FIXED_LOCK_UNTIL = Instant.parse("2024-03-01T00:00:00Z");

    /** SHA-256 of the literal ASCII {@code "verify-token-golden"}. */
    public static final String PENDING_TOKEN_HASH_HEX =
            "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08";

    public static byte[] pendingTokenHash() {
        return HexFormat.of().parseHex(PENDING_TOKEN_HASH_HEX);
    }

    public record Fixture(String json, String externalId, String plaintext) {}

    /**
     * Build the canonical fixture set with hashes produced by the supplied
     * {@link PasswordHasher}. The same encoder is used by registration and by
     * rehash-on-login, so a fixture generated here is verified by the very
     * code paths we ship — no fake hashes ever live in the corpus.
     */
    public static Map<String, Fixture> withGeneratedHashes(PasswordHasher hasher) {
        String credentialHash = hasher.hash(CREDENTIAL_PLAINTEXT);
        String lockedHash = hasher.hash(LOCKED_PLAINTEXT);
        String pendingHash = hasher.hash(PENDING_PLAINTEXT);

        Map<String, Fixture> fixtures = new LinkedHashMap<>();
        fixtures.put(CREDENTIAL_USER_ID, new Fixture("""
                {
                  "id": "%s",
                  "email": "credential@example.invalid",
                  "name": "Credential User",
                  "passwordHash": "%s",
                  "image": null,
                  "provider": "credentials",
                  "emailVerified": "%s",
                  "failedLoginAttempts": 0,
                  "lockedUntil": null,
                  "createdAt": "%s",
                  "updatedAt": "%s",
                  "oauthAccounts": []
                }
                """.formatted(CREDENTIAL_USER_ID, credentialHash, FIXED_VERIFIED_AT,
                        FIXED_CREATED_AT, FIXED_UPDATED_AT),
                CREDENTIAL_USER_ID, CREDENTIAL_PLAINTEXT));
        fixtures.put(LOCKED_USER_ID, new Fixture("""
                {
                  "id": "%s",
                  "email": "locked@example.invalid",
                  "name": "Locked User",
                  "passwordHash": "%s",
                  "image": null,
                  "provider": "credentials",
                  "emailVerified": "%s",
                  "failedLoginAttempts": 5,
                  "lockedUntil": "%s",
                  "createdAt": "%s",
                  "updatedAt": "%s",
                  "oauthAccounts": []
                }
                """.formatted(LOCKED_USER_ID, lockedHash, FIXED_VERIFIED_AT, FIXED_LOCK_UNTIL,
                        FIXED_CREATED_AT, FIXED_UPDATED_AT),
                LOCKED_USER_ID, LOCKED_PLAINTEXT));
        fixtures.put(PENDING_USER_ID, new Fixture("""
                {
                  "id": "%s",
                  "email": "pending@example.invalid",
                  "name": "Pending User",
                  "passwordHash": "%s",
                  "image": null,
                  "provider": "credentials",
                  "emailVerified": null,
                  "failedLoginAttempts": 0,
                  "lockedUntil": null,
                  "createdAt": "%s",
                  "updatedAt": "%s",
                  "oauthAccounts": [],
                  "emailVerificationTokenHash": "%s",
                  "emailVerificationExpiresAt": "%s"
                }
                """.formatted(PENDING_USER_ID, pendingHash, FIXED_CREATED_AT, FIXED_UPDATED_AT,
                        PENDING_TOKEN_HASH_HEX, FIXED_TOKEN_EXPIRES_AT),
                PENDING_USER_ID, PENDING_PLAINTEXT));
        fixtures.put(GOOGLE_USER_ID, new Fixture("""
                {
                  "id": "%s",
                  "email": "google@example.invalid",
                  "name": "Google User",
                  "passwordHash": "",
                  "image": "https://example.invalid/google.png",
                  "provider": "google",
                  "emailVerified": "%s",
                  "failedLoginAttempts": 0,
                  "lockedUntil": null,
                  "createdAt": "%s",
                  "updatedAt": "%s",
                  "oauthAccounts": [
                    { "provider": "google", "providerAccountId": "google-account-id-1" }
                  ]
                }
                """.formatted(GOOGLE_USER_ID, FIXED_VERIFIED_AT,
                        FIXED_CREATED_AT, FIXED_UPDATED_AT),
                GOOGLE_USER_ID, null));
        fixtures.put(FACEBOOK_USER_ID, new Fixture("""
                {
                  "id": "%s",
                  "email": "facebook@example.invalid",
                  "name": "Facebook User",
                  "passwordHash": "",
                  "image": "https://example.invalid/facebook.png",
                  "provider": "facebook",
                  "emailVerified": "%s",
                  "failedLoginAttempts": 0,
                  "lockedUntil": null,
                  "createdAt": "%s",
                  "updatedAt": "%s",
                  "oauthAccounts": [
                    { "provider": "facebook", "providerAccountId": "facebook-account-id-1" }
                  ]
                }
                """.formatted(FACEBOOK_USER_ID, FIXED_VERIFIED_AT,
                        FIXED_CREATED_AT, FIXED_UPDATED_AT),
                FACEBOOK_USER_ID, null));
        fixtures.put(DUPLICATE_USER_ID, new Fixture("""
                {
                  "id": "%s",
                  "email": "duplicate@example.invalid",
                  "name": "Duplicate Credential User",
                  "passwordHash": "%s",
                  "image": null,
                  "provider": "credentials",
                  "emailVerified": null,
                  "failedLoginAttempts": 0,
                  "lockedUntil": null,
                  "createdAt": "%s",
                  "updatedAt": "%s",
                  "oauthAccounts": []
                }
                """.formatted(DUPLICATE_USER_ID, credentialHash, FIXED_CREATED_AT,
                        FIXED_UPDATED_AT),
                DUPLICATE_USER_ID, CREDENTIAL_PLAINTEXT));
        fixtures.put(EMAIL_CLASH_USER_ID, new Fixture("""
                {
                  "id": "%s",
                  "email": "shared@example.invalid",
                  "name": "Email Clash User",
                  "passwordHash": "%s",
                  "image": null,
                  "provider": "credentials",
                  "emailVerified": null,
                  "failedLoginAttempts": 0,
                  "lockedUntil": null,
                  "createdAt": "%s",
                  "updatedAt": "%s",
                  "oauthAccounts": []
                }
                """.formatted(EMAIL_CLASH_USER_ID, credentialHash, FIXED_CREATED_AT,
                        FIXED_UPDATED_AT),
                EMAIL_CLASH_USER_ID, CREDENTIAL_PLAINTEXT));
        return fixtures;
    }

    /** JSON array body ready for {@link LegacyUsersTransformer#transform(String)}. */
    public static String asUsersJson(Map<String, Fixture> fixtures) {
        StringBuilder array = new StringBuilder("[");
        boolean first = true;
        for (Fixture fixture : fixtures.values()) {
            if (!first) {
                array.append(',');
            }
            first = false;
            array.append('\n').append(fixture.json());
        }
        array.append("\n]");
        return array.toString();
    }
}
