import { NextResponse } from 'next/server';
import { requireAuthenticatedUserId } from '@/lib/auth/guards';
import { requireTreePermission } from '@/lib/auth/rbac';
import { getMembers, getRelationships } from '@/lib/blob/readers';
import { resolveSourceScope } from '@/lib/algorithms/source-scope';
import { canAccessTree } from '@/lib/auth/rbac';
import { getTrees } from '@/lib/blob/readers';
import { compositeConfigService } from '@/lib/services/composite-config-service';
import { compositeResolver } from '@/lib/services/composite-resolver';
import { treeRouteError } from '@/lib/services/tree-api-errors';
import { suggestIdentities } from '@/lib/composite/identity-matching';

export const runtime = 'nodejs';
type Context = { params: { treeId: string; operation?: string[] } };
const revision = (request: Request) => { const value = Number(request.headers.get('if-match') ?? new URL(request.url).searchParams.get('revision')); if (!Number.isInteger(value) || value < 0) throw new SyntaxError('revision is required'); return value; };
export async function GET(_request: Request, { params }: Context) { try { const userId = await requireAuthenticatedUserId(); await requireTreePermission(params.treeId, userId, 'READ'); const [action] = params.operation ?? []; if (!action) return NextResponse.json(await compositeConfigService.getConfig(params.treeId)); if (action === 'resolve') return NextResponse.json(await compositeResolver.resolveForUser(params.treeId, userId)); if (action === 'identity-suggestions') { const config = await compositeConfigService.getConfig(params.treeId); const trees = new Map((await getTrees()).map((tree) => [tree.id, tree])); const authorized = config.sources.filter((source) => { const tree = trees.get(source.sourceTreeId); return tree && canAccessTree(tree, userId, 'READ'); }); const sources = await Promise.all(authorized.map(async (source) => { const [members, relationships] = await Promise.all([getMembers(source.sourceTreeId), getRelationships(source.sourceTreeId)]); const scoped = resolveSourceScope(members, relationships, [], [], source); return { treeId: source.sourceTreeId, members: scoped.members, relationships: scoped.relationships }; })); return NextResponse.json(suggestIdentities(sources, config.identityGroups)); } return NextResponse.json({ error: { code: 'NOT_FOUND' } }, { status: 404 }); } catch (error) { return treeRouteError(error); } }
export async function POST(request: Request, { params }: Context) { try { const userId = await requireAuthenticatedUserId(); const [action] = params.operation ?? []; if (action === 'validate') return NextResponse.json(await compositeResolver.validate(params.treeId, userId)); if (action === 'publish') { const validation = await compositeResolver.validate(params.treeId, userId); if (!validation.valid) return NextResponse.json(validation, { status: 422 }); return NextResponse.json(await compositeConfigService.publish(params.treeId, userId, revision(request))); } const body = await request.json(); if (action === 'preview-source') return NextResponse.json(await compositeConfigService.previewSource(params.treeId, userId, body)); if (action === 'sources') return NextResponse.json(await compositeConfigService.addSource(params.treeId, userId, body, revision(request)), { status: 201 }); if (action === 'identity-groups') return NextResponse.json(await compositeConfigService.upsertIdentityGroup(params.treeId, userId, null, body, revision(request)), { status: 201 }); if (action === 'relationships') return NextResponse.json(await compositeConfigService.createCrossTreeRelationship(params.treeId, userId, body, revision(request)), { status: 201 }); return NextResponse.json({ error: { code: 'NOT_FOUND' } }, { status: 404 }); } catch (error) { return treeRouteError(error); } }
export async function PUT(request: Request, { params }: Context) { try { const userId = await requireAuthenticatedUserId(); const [resource, id] = params.operation ?? []; const body = await request.json(); if (resource === 'sources' && id) return NextResponse.json(await compositeConfigService.updateSource(params.treeId, userId, id, body, revision(request))); if (resource === 'identity-groups' && id) return NextResponse.json(await compositeConfigService.upsertIdentityGroup(params.treeId, userId, id, body, revision(request))); return NextResponse.json({ error: { code: 'NOT_FOUND' } }, { status: 404 }); } catch (error) { return treeRouteError(error); } }
export async function DELETE(request: Request, { params }: Context) { try { const userId = await requireAuthenticatedUserId(); const [resource, id] = params.operation ?? []; if (resource === 'sources' && id) await compositeConfigService.removeSource(params.treeId, userId, id, revision(request)); else if (resource === 'identity-groups' && id) await compositeConfigService.removeIdentityGroup(params.treeId, userId, id, revision(request)); else if (resource === 'relationships' && id) await compositeConfigService.deleteCrossTreeRelationship(params.treeId, userId, id, revision(request)); else return NextResponse.json({ error: { code: 'NOT_FOUND' } }, { status: 404 }); return new NextResponse(null, { status: 204 }); } catch (error) { return treeRouteError(error); } }
