{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels: { release: prometheus }
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  endpoints:
    - { port: http, path: /actuator/prometheus, interval: 30s }
{{- end }}
